
version: '3'
services :
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - database.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

  admin:
    image: adminer
    container_name: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080

volumes:
  postgres-db:
